name: CI
# This workflow is triggered on pushes
on:
  push:
    branches: [ main, beta ]
    # Publish semver tags as releases.
  release:
    types: [published]
jobs:
  test:
    uses: ${{ github.workspace }}/.github/workflows/development.yml
    name: Test
  test-coverage:
    name: Test Coverage Upload
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - name: Upload coverage reports
        uses: codecov/codecov-action@v2
        with:
          files: ${{ github.workspace }}/backend-coverage.txt,${{ github.workspace }}/lcov.info
          flags: unittests
          fail_ci_if_error: true
          verbose: true
  storybook:
    name: Storybook Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: cd frontend && yarn install
      - uses: chromaui/action@v1
        with:
          workingDir: frontend
          buildScriptName: "build-storybook"
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
